### PR TITLE
[502879] Streamlined plugin metadata

### PR DESCRIPTION
**Pull request by kthoms**
Signed-off-by: Karsten Thoms <karsten.thoms@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=502879

**Comment by spoenemann** [comment]
The name of the Entities example is outdated: it was originally copied from the IDEA project, but has now become a separate example. So the correct name should be "Web Entities Example".

**Comment by kthoms** [comment]
Updated.

**Comment by spoenemann** [comment]
Same for the corresponding IDE project (sorry if I'm picky :-)

**Comment by kthoms** [comment]
Updated. NP, the issue is about pickyness :)

**Pull request merged**
