### PR TITLE
[eclipse/xtext#1434] Explicit agent configuration

### PR DESCRIPTION
**Pull request by kthoms**
Remove tools section, since appropriate tools are installed in the
container.

Signed-off-by: Karsten Thoms <karsten.thoms@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
@cdietrich please have a look at failure on server

**Comment by cdietrich** [comment]
@kthoms is there something that destroys npm?

**Comment by cdietrich** [comment]
i also dont know if npm version is to old or somethign is bad with the base image etc

**Comment by cdietrich** [comment]
i propose to replace this with 
https://github.com/eclipse/xtext-web/pull/124

**Comment by kthoms** [comment]
OK, this one is obsolete.

**Pull request closed without merging**
