### PR TITLE
Fixed Issue #39 Enabling  CORS when requesting xtext services crossdomain 

### PR DESCRIPTION
**Pull request by alfrye**
When you are using CrossDomain access to request data from the Xtext Services you will receive Error 404 because the xtext resources can not be found. I have added a setting on the client that can be passed into the options for the CreateEditor that will allow the request to the xtext services to enable cors for the request.  On the jetty server I enabled the CORS filter in order to set the correct response headers. 

If it is more desirable I can also modify the XtextServlet.xtend to send back the proper headings.

### CODE REVIEW

**Comment by cdietrich** [comment]
can you please

- rebase on eclipse/master
- signoff the commit
- sign the cla

**Comment by alfrye** [comment]
When I got the error about the cla I went through the process of filling out the form on the eclipse site for the ECLA I believe

**Comment by cdietrich** [comment]
Yes but you should signoff and rebasw the commit

**Comment by cdietrich** [comment]
@waynebeaton how does the ip validation pick the cla email it checks against?

**Comment by alfrye** [comment]
@cdietrich  I think I found the issue, my .gitconfig was setup to the username and email for my 
corporate repo and not my github repo. I have now added the correct information to my git config for my github repo. this there a way to fix the user name on the pull request

**Comment by cdietrich** [comment]
I think you still need to rebase and signoff the commit

**Comment by cdietrich** [comment]
Easiest might be to 
Update from eclipse master
Create a new branch
Commit again
New pullrequest

**Comment by alfrye** [comment]
That is what I am thinking as well.  Do we want to close out this pull request also

**Comment by cdietrich** [comment]
Yes

**Pull request closed without merging**
