### PR TITLE
Automatic changes by Buildship

### PR DESCRIPTION
**Pull request by kthoms**
These changes were automatically done by Buildship when setting up a new
workspace with Oomph. Buildship version is 3.1.0.

Signed-off-by: Karsten Thoms <karsten.thoms@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
hmm i dont have these changes @kthoms

**Comment by cdietrich** [comment]
e.g. `<attribute name="ignore_optional_problems" value="true"/>` is something we want on generated code. there is even code in
`gradle/default-project-layout.gradle`and `gradle/eclipse-project-layout.gradle` that creates this

**Comment by cdietrich** [comment]
tested this on a third machine. still cannot reproduce
=> @kthoms i wonder how you got these files

**Comment by cdietrich** [comment]
ping @kthoms

**Comment by cdietrich** [comment]
ping @kthoms

**Comment by cdietrich** [comment]
ping @kthoms

**Comment by cdietrich** [comment]
since there is no feedback i will close the PR

**Comment by kthoms** [comment]
Sorry, did not see that request. I just oomphed a fresh workspace. Will open another PR when I face it again.

**Pull request closed without merging**
