### PR TITLE
Move to Maven/Tycho for projects and build infrastructure

### PR DESCRIPTION
**Pull request by LorenzoBettini**
See https://github.com/eclipse/xtext-web/issues/400

### CODE REVIEW

**Comment by cdietrich** [comment]
@LorenzoBettini what is the correct entry pom. the one in the root does not seem too

**Comment by LorenzoBettini** [comment]
> @LorenzoBettini what is the correct entry pom. the one in the root does not seem too

You mean the one for building (reactor)?

I changed the parent POM NOT to be also the reactor/aggregator. The one for running the build is called (in all git repositories) `org.eclipse.xtext.maven.releng`. That's the one for the Maven build. For the tycho build is `org.eclipse.xtext.p2.releng`. Of course, in this repository you only have `org.eclipse.xtext.maven.releng`.

See also the `maven-build.sh` used in JIRO

**Comment by LorenzoBettini** [comment]
@cdietrich WARNING: if you had previously run the Maven build in my branch and want to try my latest commit, please first remove the directory `/org.eclipse.xtext.web/build` or you'll end up with duplicated resources in the JAR.

**Comment by cdietrich** [comment]
with the repo merge done this is obsolete

**Pull request closed without merging**
