### PR TITLE
Use IDE modules in web infrastructure

### LINKED ISSUE #6: Use IdeModule in WebStandaloneSetup
The newly introduce IdeModule now contains some bindings that were previously generated into the WebModule. The WebStandaloneSetup should include the IdeModule. For this to work properly the binding of ExecutorServices should be adapted such that it works both for the LanguageServer and the Web enviroments.

### PR DESCRIPTION
**Pull request by spoenemann**
Fixes #6.

Depends on eclipse/xtext-core#143 and eclipse/xtext-extras#65.

### CODE REVIEW

**Comment by cdietrich** [comment]
@spoenemann will you push another pullrequest for the fragments and the wizard?

**Comment by spoenemann** [comment]
> will you push another pullrequest for the fragments and the wizard?

The fragments are handled in eclipse/xtext-core#143. The wizard doesn't need any change.

**Comment by cdietrich** [comment]
@spoenemann  sure? see WebProjectDescriptor

**Comment by spoenemann** [comment]
WebProjectDescriptor creates only the build files. The WebIntegrationFragment change is here: https://github.com/eclipse/xtext-core/pull/143/files#diff-223760934fe1903552c8f9e97f6e8fdf

**Comment by cdietrich** [comment]
yes but both files contain stuff like

```
	static val REQUIREJS_VERSION = '2.2.0'
	static val REQUIREJS_TEXT_VERSION = '2.0.15'
	static val JQUERY_VERSION = '2.2.3'
	static val ACE_VERSION = '1.2.2'
	static val CODEMIRROR_VERSION = '5.13.2'
```

and i dont see a change to this e.g. in https://github.com/eclipse/xtext-core/pull/143/files#diff-223760934fe1903552c8f9e97f6e8fdf

**Comment by spoenemann** [comment]
My changes here affect only the example in the repository, not the projects generated by the wizard and the generator. We can update those too, but that's not critical for this week's beta release.

**Comment by cdietrich** [comment]
Yes but we should make sure it does not get lost since the examples are no longer representative

**Comment by cdietrich** [comment]
This I wonder why you changed them at all

**Comment by spoenemann** [comment]
Just checking whether xtext-web still works with the current versions.

**Pull request merged**
